image: docker.io/nbatalha/kube-on-docker:latest

# See
# https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-in-docker-executor
services:
  - docker:dind

stages:
  - build
  - release

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

build:
    stage: build
    script:
      - make push

push_prod:
    stage: release
    script:
      - make release
    environment: prod
    when: manual
    only:
      - master
