image: docker.io/nbatalha/kube-on-docker:latest

# See
# https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-in-docker-executor
services:
  - docker:dind

stages:
  - build
  - release

before_script:
  - mkdir $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

build:
    stage: build
    script:
      - make push

push_prod:
    stage: release
    script:
      - make release
    environment: prod
    when: manual
    only:
      - master
